server_port: 8080
log_level: debug
postgres:
  host: localhost
  port: 5432
  db: chats
  user: chats_service
  password: secret
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: 3m
  conn_max_idle_time: 1m
