// Code generated by ogen, DO NOT EDIT.
package api

type BanUserRes interface {
	banUserRes()
}

type CheckAccessRes interface {
	checkAccessRes()
}

type CreateChatRes interface {
	createChatRes()
}

type CreateRoleRes interface {
	createRoleRes()
}

type DeleteChatRes interface {
	deleteChatRes()
}

type DeleteRoleRes interface {
	deleteRoleRes()
}

type GetChatByIdRes interface {
	getChatByIdRes()
}

type GetJoinCodeRes interface {
	getJoinCodeRes()
}

type GetMyRoleRes interface {
	getMyRoleRes()
}

type GetRoleByIdRes interface {
	getRoleByIdRes()
}

type JoinChatRes interface {
	joinChatRes()
}

type LeaveChatRes interface {
	leaveChatRes()
}

type ListBannedUsersRes interface {
	listBannedUsersRes()
}

type ListChatsRes interface {
	listChatsRes()
}

type ListMembersRes interface {
	listMembersRes()
}

type ListRolesRes interface {
	listRolesRes()
}

type SetRoleRes interface {
	setRoleRes()
}

type UnbanUserRes interface {
	unbanUserRes()
}

type UpdateChatRes interface {
	updateChatRes()
}

type UpdateRoleRes interface {
	updateRoleRes()
}
