// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	BanUserOperation         OperationName = "BanUser"
	CheckAccessOperation     OperationName = "CheckAccess"
	CreateChatOperation      OperationName = "CreateChat"
	CreateRoleOperation      OperationName = "CreateRole"
	DeleteChatOperation      OperationName = "DeleteChat"
	DeleteRoleOperation      OperationName = "DeleteRole"
	GetChatByIdOperation     OperationName = "GetChatById"
	GetJoinCodeOperation     OperationName = "GetJoinCode"
	GetMyRoleOperation       OperationName = "GetMyRole"
	GetRoleByIdOperation     OperationName = "GetRoleById"
	JoinChatOperation        OperationName = "JoinChat"
	LeaveChatOperation       OperationName = "LeaveChat"
	ListBannedUsersOperation OperationName = "ListBannedUsers"
	ListChatsOperation       OperationName = "ListChats"
	ListMembersOperation     OperationName = "ListMembers"
	ListRolesOperation       OperationName = "ListRoles"
	SetRoleOperation         OperationName = "SetRole"
	UnbanUserOperation       OperationName = "UnbanUser"
	UpdateChatOperation      OperationName = "UpdateChat"
	UpdateRoleOperation      OperationName = "UpdateRole"
)
