// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/google/uuid"
)

type BearerAuth struct {
	Token string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

type ChatId int

// Ref: #/components/responses/chatNotFoundResponse
type ChatNotFoundResponse struct{}

func (*ChatNotFoundResponse) listMessagesRes() {}
func (*ChatNotFoundResponse) sendMessageRes()  {}

// DeleteMessageNoContent is response for DeleteMessage operation.
type DeleteMessageNoContent struct{}

func (*DeleteMessageNoContent) deleteMessageRes() {}

// DeleteMessageNotFound is response for DeleteMessage operation.
type DeleteMessageNotFound struct{}

func (*DeleteMessageNotFound) deleteMessageRes() {}

// GetMessageByIdNotFound is response for GetMessageById operation.
type GetMessageByIdNotFound struct{}

func (*GetMessageByIdNotFound) getMessageByIdRes() {}

// Ref: #/components/responses/internalErrorResponse
type InternalErrorResponse struct{}

func (*InternalErrorResponse) deleteMessageRes()  {}
func (*InternalErrorResponse) getMessageByIdRes() {}
func (*InternalErrorResponse) listMessagesRes()   {}
func (*InternalErrorResponse) sendMessageRes()    {}
func (*InternalErrorResponse) updateMessageRes()  {}

type InvalidInputResponse struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *InvalidInputResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *InvalidInputResponse) SetMessage(val string) {
	s.Message = val
}

func (*InvalidInputResponse) deleteMessageRes()  {}
func (*InvalidInputResponse) getMessageByIdRes() {}
func (*InvalidInputResponse) listMessagesRes()   {}
func (*InvalidInputResponse) sendMessageRes()    {}
func (*InvalidInputResponse) updateMessageRes()  {}

type ListMessagesOKApplicationJSON []Message

func (*ListMessagesOKApplicationJSON) listMessagesRes() {}

// Ref: #/components/schemas/message
type Message struct {
	ID            MessageId `json:"id"`
	SenderID      UserId    `json:"sender_id"`
	Message       string    `json:"message"`
	Edited        bool      `json:"edited"`
	SendTimestamp int       `json:"send_timestamp"`
}

// GetID returns the value of ID.
func (s *Message) GetID() MessageId {
	return s.ID
}

// GetSenderID returns the value of SenderID.
func (s *Message) GetSenderID() UserId {
	return s.SenderID
}

// GetMessage returns the value of Message.
func (s *Message) GetMessage() string {
	return s.Message
}

// GetEdited returns the value of Edited.
func (s *Message) GetEdited() bool {
	return s.Edited
}

// GetSendTimestamp returns the value of SendTimestamp.
func (s *Message) GetSendTimestamp() int {
	return s.SendTimestamp
}

// SetID sets the value of ID.
func (s *Message) SetID(val MessageId) {
	s.ID = val
}

// SetSenderID sets the value of SenderID.
func (s *Message) SetSenderID(val UserId) {
	s.SenderID = val
}

// SetMessage sets the value of Message.
func (s *Message) SetMessage(val string) {
	s.Message = val
}

// SetEdited sets the value of Edited.
func (s *Message) SetEdited(val bool) {
	s.Edited = val
}

// SetSendTimestamp sets the value of SendTimestamp.
func (s *Message) SetSendTimestamp(val int) {
	s.SendTimestamp = val
}

func (*Message) getMessageByIdRes() {}
func (*Message) sendMessageRes()    {}
func (*Message) updateMessageRes()  {}

type MessageId int

// Ref: #/components/schemas/messageInput
type MessageInput struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *MessageInput) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *MessageInput) SetMessage(val string) {
	s.Message = val
}

// Ref: #/components/responses/unauthenticatedResponse
type UnauthenticatedResponse struct{}

func (*UnauthenticatedResponse) deleteMessageRes()  {}
func (*UnauthenticatedResponse) getMessageByIdRes() {}
func (*UnauthenticatedResponse) listMessagesRes()   {}
func (*UnauthenticatedResponse) sendMessageRes()    {}
func (*UnauthenticatedResponse) updateMessageRes()  {}

// Ref: #/components/responses/unauthorizedResponse
type UnauthorizedResponse struct{}

func (*UnauthorizedResponse) deleteMessageRes()  {}
func (*UnauthorizedResponse) getMessageByIdRes() {}
func (*UnauthorizedResponse) listMessagesRes()   {}
func (*UnauthorizedResponse) sendMessageRes()    {}
func (*UnauthorizedResponse) updateMessageRes()  {}

// UpdateMessageNotFound is response for UpdateMessage operation.
type UpdateMessageNotFound struct{}

func (*UpdateMessageNotFound) updateMessageRes() {}

type UserId uuid.UUID
