// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	DeleteMessageOperation  OperationName = "DeleteMessage"
	GetMessageByIdOperation OperationName = "GetMessageById"
	ListMessagesOperation   OperationName = "ListMessages"
	SendMessageOperation    OperationName = "SendMessage"
	UpdateMessageOperation  OperationName = "UpdateMessage"
)
