// Code generated by ogen, DO NOT EDIT.
package api

type DeleteMessageRes interface {
	deleteMessageRes()
}

type GetMessageByIdRes interface {
	getMessageByIdRes()
}

type ListMessagesRes interface {
	listMessagesRes()
}

type SendMessageRes interface {
	sendMessageRes()
}

type UpdateMessageRes interface {
	updateMessageRes()
}
