// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// DeleteMessage implements deleteMessage operation.
//
// Delete message from chat.
//
// DELETE /messages/{messageId}
func (UnimplementedHandler) DeleteMessage(ctx context.Context, params DeleteMessageParams) (r DeleteMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMessageById implements getMessageById operation.
//
// Get message in chat.
//
// GET /messages/{messageId}
func (UnimplementedHandler) GetMessageById(ctx context.Context, params GetMessageByIdParams) (r GetMessageByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMessages implements listMessages operation.
//
// Get messages for chat.
//
// GET /messages
func (UnimplementedHandler) ListMessages(ctx context.Context, params ListMessagesParams) (r ListMessagesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SendMessage implements sendMessage operation.
//
// Send new message to chat.
//
// POST /messages
func (UnimplementedHandler) SendMessage(ctx context.Context, req *MessageInput, params SendMessageParams) (r SendMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateMessage implements updateMessage operation.
//
// Update message in chat.
//
// PUT /messages/{messageId}
func (UnimplementedHandler) UpdateMessage(ctx context.Context, req *MessageInput, params UpdateMessageParams) (r UpdateMessageRes, _ error) {
	return r, ht.ErrNotImplemented
}
