// Code generated by ogen, DO NOT EDIT.
package api

type ChangePasswordRes interface {
	changePasswordRes()
}

type CheckTokenRes interface {
	checkTokenRes()
}

type GetMeRes interface {
	getMeRes()
}

type GetUserByIdRes interface {
	getUserByIdRes()
}

type SignInRes interface {
	signInRes()
}

type SignUpRes interface {
	signUpRes()
}

type UpdateMeRes interface {
	updateMeRes()
}
