services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: messages-service
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: messages
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  

  
  redis:
    image: redis:7
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
