services:
  postgres:
    container_name: postgres
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=users_service
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d users -U users_service
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  migrate:
    image: migrate/migrate
    container_name: migrate
    volumes:
      - ./migrations:/migrations
    entrypoint: >
      sh -c 'migrate -path /migrations \
        -database "postgres://users_service:secret@postgres:5432/users?sslmode=disable" up
      '
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
