version: "3.8"

services:
  chats-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.chats-service
    environment:
      - SERVER_PORT=9090
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=chats
      - POSTGRES_USER=chats_service
      - POSTGRES_PASSWORD=secret
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    ports:
      - 9090:9090

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/swagger/swagger.yml
    volumes:
      - ../api:/swagger
    ports:
      - 5000:8080

  postgres:
    container_name: postgres
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_DB=chats
      - POSTGRES_USER=chats_service
      - POSTGRES_PASSWORD=secret
    volumes:
      - chats_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -d chats -U chats_service
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  nginx:
    image: nginx:1.27.2-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - chats-service
    ports:
      - 8080:8080

  migrate:
    image: migrate/migrate
    container_name: migrate
    volumes:
      - ./migrations:/migrations
    entrypoint: >
      sh -c 'migrate -path /migrations \
        -database "postgres://chats_service:secret@postgres:5432/chats?sslmode=disable" up
      '
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  chats_postgres_data:
